# Generated by Django 6.0 on 2026-01-04 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('ficheiro', models.FileField(upload_to='biblioteca/')),
                ('observacoes', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.area')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('estado', models.CharField(choices=[('PLN', 'Planeado'), ('AND', 'Em Andamento'), ('CON', 'Concluído')], default='PLN', max_length=3)),
                ('prioridade', models.CharField(blank=True, max_length=50)),
                ('codigo_interno', models.CharField(blank=True, max_length=20)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
