# Generated by Django 6.0 on 2026-01-04 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='codigo_interno',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='prioridade',
        ),
        migrations.AddField(
            model_name='projeto',
            name='campo_custom_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personalizado 1 (ex: Prioridade)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='campo_custom_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personalizado 2 (ex: Código)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='campo_custom_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personalizado 3 (ex: Link)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='campo_custom_4',
            field=models.TextField(blank=True, null=True, verbose_name='Personalizado 4 (ex: Notas Extras)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='estado',
            field=models.CharField(choices=[('PLN', 'Planeado'), ('AND', 'Em Andamento'), ('CON', 'Concluído')], default='PLN', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
