# Generated by Django 6.0 on 2026-01-04 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_projeto_codigo_interno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='custos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='projeto',
            name='orcamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='projeto',
            name='receita',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='campo_custom_1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Prioridade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='campo_custom_2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Código Interno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='campo_custom_3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Link Externo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='campo_custom_4',
            field=models.TextField(blank=True, default='', verbose_name='Observações Extras'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='estado',
            field=models.CharField(choices=[('PLN', 'Planeado'), ('AND', 'Em Andamento'), ('CON', 'Concluído')], default='PLN', max_length=3),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
