# Generated by Django 6.0 on 2026-01-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_projeto_custos_projeto_orcamento_projeto_receita_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='data_fim',
            new_name='data_fIM',
        ),
        migrations.RemoveField(
            model_name='material',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='material',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='campo_custom_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='C1'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='campo_custom_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='C2'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='campo_custom_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='C3'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='campo_custom_4',
            field=models.TextField(blank=True, verbose_name='C4'),
        ),
    ]
