# Generated by Django 6.0 on 2026-01-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_rename_data_fim_projeto_data_fim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='data_fIM',
            new_name='data_fim',
        ),
    ]
